[theme]

# Primary accent for interactive elements
primaryColor = '#9BA4B5'

# Background color for the main content area
backgroundColor = '#00215A'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#3059A0'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"